[build-system]
requires = ["setuptools>=58.0.4", "wheel>=0.37.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "rsxml"
version = "{file = \"rsxml/__version__.py\", key = \"__version__\"}"
description = "Riverscapes XML helpers for use across Python3 open-source GIS Stack"
authors = [
  { name="Matt Reimer", email="info@northarrowresearch.com"}
]
license = "MIT"
homepage = "https://github.com/Riverscapes/RiverscapesXML"
repository = "https://github.com/Riverscapes/RiverscapesXML"
documentation = "https://github.com/Riverscapes/RiverscapesXML"

[tool.poetry.dependencies]
python = "^3.10.0"
semver = ">=2.10.2"
argparse = "*"
readme="README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system.sdist]
formats = ["gztar", "zip"]
