<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis styleCategories="AllStyleCategories" maxScale="0" version="3.16.10-Hannover" hasScaleBasedVisibilityFlag="0" minScale="0">
  <flags>
    <Identifiable>1</Identifiable>
    <Removable>1</Removable>
    <Searchable>1</Searchable>
  </flags>
  <temporal fetchMode="0" enabled="0" mode="0">
    <fixedRange>
      <start></start>
      <end></end>
    </fixedRange>
  </temporal>
  <customproperties>
    <property key="WMSBackgroundLayer" value="false"/>
    <property key="WMSPublishDataSourceUrl" value="false"/>
    <property key="embeddedWidgets/count" value="0"/>
  </customproperties>
  <pipe>
    <provider>
      <resampling zoomedOutResamplingMethod="nearestNeighbour" enabled="false" zoomedInResamplingMethod="nearestNeighbour" maxOversampling="2"/>
    </provider>
    <rasterrenderer alphaBand="-1" nodataColor="" opacity="0.6" band="1" type="paletted">
      <rasterTransparency/>
      <minMaxOrigin>
        <limits>None</limits>
        <extent>WholeRaster</extent>
        <statAccuracy>Estimated</statAccuracy>
        <cumulativeCutLower>0.02</cumulativeCutLower>
        <cumulativeCutUpper>0.98</cumulativeCutUpper>
        <stdDevFactor>2</stdDevFactor>
      </minMaxOrigin>
      <colorPalette>
        <paletteEntry color="#ffffff" value="7008" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7009" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7010" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7011" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7012" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7013" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7014" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7015" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7016" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7017" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7018" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7019" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7020" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7021" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7022" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7023" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7024" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7025" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7026" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7027" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7028" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7029" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7030" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7031" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7032" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7033" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7034" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7035" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7036" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7037" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7038" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7039" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7041" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7042" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7043" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7044" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7045" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7046" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7047" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7048" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7049" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7050" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7051" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7052" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7053" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7054" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7055" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7056" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7057" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7058" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7059" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7060" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7061" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7062" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7063" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7064" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7065" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7066" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7067" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7068" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7069" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7070" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7071" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7072" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7073" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7074" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7075" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7076" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7077" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7078" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7079" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7080" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7081" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7082" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7083" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7084" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7085" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7086" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7087" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7088" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7090" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7091" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7092" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7093" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7094" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7096" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7097" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7098" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7099" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7100" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7101" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7102" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7103" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7104" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7105" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7106" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7107" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7108" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7109" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7110" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7111" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7112" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7113" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7114" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7115" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7116" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7117" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7118" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7119" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7120" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7121" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7122" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7123" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7124" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7125" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7126" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7127" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7128" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7129" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7130" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7131" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7132" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7133" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7134" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7135" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7136" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7137" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7138" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7139" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7140" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7141" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7142" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7143" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7144" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7145" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7146" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7147" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7148" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7149" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7150" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7151" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7152" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7153" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7156" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7157" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7158" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7159" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7161" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7165" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7166" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7167" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7168" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7169" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7170" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7171" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7172" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7173" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7174" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7177" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7178" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7179" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7191" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7192" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7193" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7195" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7196" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7197" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7198" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7199" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7200" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7207" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7234" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7238" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7239" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7240" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7241" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7242" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7243" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7247" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7248" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7249" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7250" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7256" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7260" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7261" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7262" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7263" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7264" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7265" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7268" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7270" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7272" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7286" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7290" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7291" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7292" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7295" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7296" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7297" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7298" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7299" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7301" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7302" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7303" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7304" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7305" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7306" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7307" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7308" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7309" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7310" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7311" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7312" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7313" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7314" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7315" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7316" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7317" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7318" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7320" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7321" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7322" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7323" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7324" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7325" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7326" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7327" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7328" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7329" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7330" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7331" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7333" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7334" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7335" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7336" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7337" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7338" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7339" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7340" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7342" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7343" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7346" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7347" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7348" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7349" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7350" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7351" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7352" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7353" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7355" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7356" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7357" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7358" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7360" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7361" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7362" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7363" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7364" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7366" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7367" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7368" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7369" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7370" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7371" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7372" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7375" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7376" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7377" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7378" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7379" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7380" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7381" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7382" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7383" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7384" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7385" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7387" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7388" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7390" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7391" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7392" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7393" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7394" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7395" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7396" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7397" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7398" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7400" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7401" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7403" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7405" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7406" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7407" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7408" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7409" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7410" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7411" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7412" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7413" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7414" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7415" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7416" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7417" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7418" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7419" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7420" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7421" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7422" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7423" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7424" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7425" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7426" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7428" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7429" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7430" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7431" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7434" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7435" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7436" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7437" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7438" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7439" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7441" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7442" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7444" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7445" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7446" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7447" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7448" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7449" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7450" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7451" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7452" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7453" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7454" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7455" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7456" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7457" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7458" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7459" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7460" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7461" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7462" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7463" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7466" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7467" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7468" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7469" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7471" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7472" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7473" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7474" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7475" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7476" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7481" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7482" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7483" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7484" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7485" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7486" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7487" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7488" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7489" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7500" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7501" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7502" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7503" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7504" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7505" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7506" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7507" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7509" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7510" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7511" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7512" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7513" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7514" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7515" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7516" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7517" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7518" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7519" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7522" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7523" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7524" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7525" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7527" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7545" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7546" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7547" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7548" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7556" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7557" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7560" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7561" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7562" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7563" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7564" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7565" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7566" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7567" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7571" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7573" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7578" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7582" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7583" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7584" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7585" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7586" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7587" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7588" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7589" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7590" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7591" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7662" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7663" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7668" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7733" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7734" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7735" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="7861" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="7867" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="7900" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7901" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7902" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7903" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7904" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7905" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7906" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7907" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7908" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7909" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7910" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7911" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7912" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7913" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7914" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7915" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7916" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7917" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7918" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7919" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7920" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7921" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7922" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7923" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7924" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7925" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7926" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7927" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7928" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7929" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7930" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7931" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7932" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7933" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7934" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7935" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7936" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7937" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7938" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7939" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7940" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7941" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7942" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7943" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7944" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7945" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7946" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7947" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7948" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7949" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7950" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7951" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7952" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7953" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7954" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7955" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7956" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7957" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7958" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7959" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7960" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7961" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7962" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7963" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7964" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7965" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7966" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7967" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7968" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7970" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7971" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7972" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7973" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7974" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7975" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7976" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7977" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7978" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7979" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7980" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7981" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7982" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7983" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7984" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7985" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7986" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7987" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7988" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7989" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7990" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7991" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7992" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7993" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7994" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7995" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7996" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7997" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7998" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="7999" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9001" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9002" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9003" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9004" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9005" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9006" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9008" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9009" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9010" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9011" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9012" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9014" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9015" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9016" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9017" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9018" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9019" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9021" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9022" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9023" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9024" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9025" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9026" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9027" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9028" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9029" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9030" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9032" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9033" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9034" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9035" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9041" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9042" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9044" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9045" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9047" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9050" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9051" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9055" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9056" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9057" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9059" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9060" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9061" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9062" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9063" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9064" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9065" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9066" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9068" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9069" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9071" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9073" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9075" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9077" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9080" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9082" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9083" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9085" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9088" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9089" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9091" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9092" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9094" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9095" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9097" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9098" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9099" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9100" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9101" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9102" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9103" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9104" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9105" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9106" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9110" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9111" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9112" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9113" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9114" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9115" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9117" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9118" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9119" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9120" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9121" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9122" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9125" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9126" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9129" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9130" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9133" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9134" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9136" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9137" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9138" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9139" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9140" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9141" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9142" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9143" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9145" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9146" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9147" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9148" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9150" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9151" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9152" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9153" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9154" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9160" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9165" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9166" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9167" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9170" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9171" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9173" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9174" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9175" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9176" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9177" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9178" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9179" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9180" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9181" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9182" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9183" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9187" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9188" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9189" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9190" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9191" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9192" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9193" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9195" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9197" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9198" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9202" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9203" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9207" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9208" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9209" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9210" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9211" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9213" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9216" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9218" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9220" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9221" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9222" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9223" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9224" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9226" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9227" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9228" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9229" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9230" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9231" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9232" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9233" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9234" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9235" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9237" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9239" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9240" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9241" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9242" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9243" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9244" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9245" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9246" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9247" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9248" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9249" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9250" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9251" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9256" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9257" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9258" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9259" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9260" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9261" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9262" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9265" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9266" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9268" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9270" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9272" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9273" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9274" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9275" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9282" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9283" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9284" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9288" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9289" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9290" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9295" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9301" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9302" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9304" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9307" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9308" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9309" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9310" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9311" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9312" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9313" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9314" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9315" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9316" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9317" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9318" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9319" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9320" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9321" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9322" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9323" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9324" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9325" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9326" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9327" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9328" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9329" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9332" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9336" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9337" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9502" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9503" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9504" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9505" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9512" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9513" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9514" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9515" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9516" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9519" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9526" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9527" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9528" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9529" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9533" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9534" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9535" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9541" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9542" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9559" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9560" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9561" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9562" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9568" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9569" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9570" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9571" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9582" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9583" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9585" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9586" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9592" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9593" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9601" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9604" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9605" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9611" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9617" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9620" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9629" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9633" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9639" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9640" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9641" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9642" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9652" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9654" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9667" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9677" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9679" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9682" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9683" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9695" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9696" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9707" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9708" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9722" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9723" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9724" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9725" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9726" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9730" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9731" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9732" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9733" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9742" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9743" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9758" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9759" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9760" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9761" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9766" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9774" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9775" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9782" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9783" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9784" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9785" alpha="255" label="Riparian"/>
        <paletteEntry color="#ffffff" value="9810" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9811" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9816" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9817" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9823" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9825" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9826" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9827" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#ffffff" value="9828" alpha="255" label="Non-Riparian"/>
        <paletteEntry color="#38A800" value="9829" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9993" alpha="255" label="Riparian"/>
        <paletteEntry color="#38A800" value="9994" alpha="255" label="Riparian"/>
      </colorPalette>
      <colorramp name="[source]" type="randomcolors"/>
    </rasterrenderer>
    <brightnesscontrast contrast="0" gamma="1" brightness="0"/>
    <huesaturation colorizeOn="0" colorizeBlue="128" colorizeStrength="100" grayscaleMode="0" colorizeGreen="128" saturation="0" colorizeRed="255"/>
    <rasterresampler maxOversampling="2"/>
    <resamplingStage>resamplingFilter</resamplingStage>
  </pipe>
  <blendMode>0</blendMode>
</qgis>
